### ISSUE TITLE
unexpected keyword argument 'expected_binsize' in example_generate_data_K562_train.py

### ISSUE THREAD

**Issue by chenkenbio** [labdevgen/3Dpredictor#57]
Hello, recently I'm interested in you work published on Genome Research. But when I tried to reproduce the results in your paper, I found the following bug:

    user@localhost:~/Documents/3Dpredictor/source$ python example_generate_data_K562_train.py 1,3,5,7,9 contacts.gz
    DEBUG:__main__:Using input folder input/K562/
    Traceback (most recent call last):
      File "example_generate_data_K562_train.py", line 66, in <module>
        expected_binsize = 25000)
    TypeError: read_files() got an unexpected keyword argument 'expected_binsize'

It seems that the keyword `expected_binsize` only appears in `source/example_generate_data_K562_train.py` and is not defined in any other scripts, which confuses me a lot. Can you give any more advice on reproducing `3Dpredictor`? Thanks a lot!

**Comment by polyaB** [comment]
> Hello, recently I'm interested in you work published on Genome Research. But when I tried to reproduce the results in your paper, I found the following bug:
> 
> ```
> user@localhost:~/Documents/3Dpredictor/source$ python example_generate_data_K562_train.py 1,3,5,7,9 contacts.gz
> DEBUG:__main__:Using input folder input/K562/
> Traceback (most recent call last):
>   File "example_generate_data_K562_train.py", line 66, in <module>
>     expected_binsize = 25000)
> TypeError: read_files() got an unexpected keyword argument 'expected_binsize'
> ```
> 
> It seems that the keyword `expected_binsize` only appears in `source/example_generate_data_K562_train.py` and is not defined in any other scripts, which confuses me a lot. Can you give any more advice on reproducing `3Dpredictor`? Thanks a lot!

Hello, I suppose that it was version incompatibility. We are constantly update our code so please, use commit de22c741325a44385aad184634ed6506a465ab62 to reproduce results. If you have any questions we will glad to help.
